Changed orders seeder. Added tests to check free watchmakers.
AlexanderBeS/atech pull request #2
Opened 2020-11-27 14:14 UTC by AlexanderBeS

Changed the orders seeder. Added tests to check which watchmakers are free.

2020-11-27 15:10 UTC, bodva requested changes

2020-11-27 15:10 UTC, bodva commented on database/seeds/WatchmakerSeeder.php
> +//            }
поубирать комменты. если тебе нужно будет вспомнить, как оно было, это можно будет найти в истории

2020-11-30 06:53 UTC, AlexanderBeS commented on database/seeds/WatchmakerSeeder.php
> +//            }
Убрал комментарий.

2020-11-30 09:47 UTC, bodva approved these changes

2020-11-30 09:47 UTC, merged